### ISSUE TITLE
Nativescript-slides is not a valid NativeScript plugin

### ISSUE THREAD

**Issue by Abdumama** [TheOriginalJosh/nativescript-slides#106]
Hi,
I'm trying to install the plugin, but when I  write the command  
`tns plugin add nativescript-slides`

I have this error:
`nativescript-slides is not a valid NativeScript plugin. Verify that the plugin package.json file contains a nativescript key and try again.
`
```
"tns-android": {
      "version": "3.0.1"
    }

```

**Comment by TheOriginalJosh** [comment]
Thank you! I can't believe I screwed this up last night. fixed in version 2.2.11

**Comment by raymallperez** [comment]
Are you gonna publish on the NativeScript plugin directory? I keep getting the error...

**Comment by TheOriginalJosh** [comment]
@raymallperez , sorry I don't follow.  your getting this error with the latest version?

**Comment by raymallperez** [comment]
@TheOriginalJosh still getting the error by running `tns plugin add nativescript-slides`.
If I add the plugin directly to the `package.json` file with the fixed version `2.2.11` and run `tns install` it's ok but is a tiny bit annoying to do it that way. :)

**Comment by TheOriginalJosh** [comment]
Hmm, that's strange, I don't know why it would be pulling down an old version.

**Comment by PeterStaev** [comment]
I can also confirm that this is a regression in version 2.2.12 (which is the latest one). If I run `tns plugin add nativescript-slides` it fails with the above error. But if I do `tns plugin add nativescript-slides@2.2.11` it works ok.

**Comment by TheOriginalJosh** [comment]
Strange, I'm going to publish a new version tonight
